### ISSUE TITLE
LL/CON/MAS/BV-13-C fails when upper/lower tester have different features

### ISSUE THREAD

**Issue by mtpr-ot** [EDTTool/EDTT#18]
Running ll_verification with different devices as upper vs. lower tester fails test LL/CON/MAS/BV-13-C, because the test pass/fail validation assumes identical feature sets.

If for instance lower tester supports BT_LE_FEAT_BIT_MIN_USED_CHAN_PROC, and upper tester does not, it fails.

**Comment by mtpr-ot** [comment]
@kruithofa, I think this happened after "_Update feature exchange to BTCore V5.0_"

**Comment by kruithofa** [comment]
> @kruithofa, I think this happened after "_Update feature exchange to BTCore V5.0_"

Pre V5.0 feature exchange returned the logical and of all features from upper tester and lower tester, so if only lower tester supports BT_LE_FEAT_BIT_MIN_USED_CHAN_PROC this bit would be set to 0
Post V5.0 the logical and only applies to octet 0, the other octets show the features supported by peer. So if lower tester supports BT_LE_FEAT_BIT_MIN_USED_CHAN_PROC this bit will be set to 1, regardless of whether the upper tester supports it or not.

So this behaviour is as expected, and I'll investigate a bit more

**Comment by mtpr-ot** [comment]
I think Thomas (@thoh-ot) has found the correct handling in the EDTT test:
`expectedMaskedFeatures = toNumber([((~LL_FEAT_BIT_MASK_VALID | upperFeatures[0]) & 0xFF) &
expectedFeatures[0]] + list(expectedFeatures[1:7]))`
Please evaluate.

**Comment by kruithofa** [comment]
I reproduced the bug, and Thomas fix looks good. I'll do some more testing before creating a PR
