### ISSUE TITLE
LL/CON/MAS/BV-74-C: initial test conditions not as specified

### ISSUE THREAD

**Issue by kruithofa** [EDTTool/EDTT#8]
As per LL testspecification LL.TS.5.1.1 chapter 4.1.5:
"If a test covers optional features and does not mention the feature exchange procedure,  the IUT shall perform the feature exchange procedure before the test procedure is executed."
It seems that the feature exchange is not run as part of the test initialisation

Other pre-test setup may be missing
This applies to other tests as well

**Comment by wopu-ot** [comment]
Is this still relevant after merging #10?

**Comment by kruithofa** [comment]
Good catch,
#10<https://github.com/EDTTool/EDTT/pull/10> fixes that one.


Regards,
Andries
